fix(ci): Apply missing gitleaks license
Resolved the error returned by gitleaks:
```
[release-baton] is an organization. License key is required.
Error: 🛑 missing gitleaks license. Go grab one at gitleaks.io and
store it as a GitHub Secret named GITLEAKS_LICENSE. For more info
about the recent breaking update, see
[here](https://github.com/gitleaks/gitleaks-action#-announcement).
```